variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

deployToHugo:
  stage: test
  script:
  - hugo
  - rsync -rlptvzP public/ syskan@christina.ie.u-ryukyu.ac.jp:/mnt/cephfs/ie-web/ie/XXXX
  - rm -rf public
  only:
  - main

